spring:
  application:
    name: bi-analytics-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CDN_F_P_U_H__Piszczek;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: myapp
    password: YourPassword123!
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        globally_quoted_identifiers: true
server:
  port: 8081
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000