spring:
  application:
    name: bi-analytics-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CDN_F_P_U_H__Piszczek;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: myapp
    password: YourPassword123!
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        globally_quoted_identifiers: true
server:
  port: 8081

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175}

app:
  jwt:
    secret: ${JWT_SECRET:myVerySecretKeyForJWTTokensThatShouldBeAtLeast32Characters}
    expiration: 86400000

aws:
  access-key: test
  secret-key: test

sqs:
  local-uri: http://localhost:4567
  launch-localstack: true
  url:
    write:
      employeeChangeQueue: http://sqs.eu-central-1.localhost.localstack.cloud:4567/000000000000/employeeChangeQueue

localstack:
  sqs:
    employeeChangeQueue: http://sqs.eu-central-1.localhost.localstack.cloud:4567/000000000000/employeeChangeQueue